syntax on

set expandtab
set tabstop=2 shiftwidth=2
set softtabstop=2
set scrolloff=4                       " At least 4 lines below the cursor
set nobackup                          " No swap files
set noswapfile
set backspace=2                       " Backspace deletes in insert mode

nmap 0 ^

