#
# nvm 
#
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

#
# prompt
#
fpath+=$HOME/.zsh/pure
autoload -U promptinit; promptinit
prompt pure

#
# general options
#
setopt extendedglob
setopt no_case_glob

#
# history options
#
export HISTSIZE=7000
export SAVEHIST=7000 # max save history on logout.

setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_REDUCE_BLANKS
setopt HIST_VERIFY
setopt INC_APPEND_HISTORY

#
# line editor options
#
# bindkey -v
# bindkey '^A' vi-beginning-of-line
# bindkey '^E' vi-end-of-line
# bindkey '^R' history-incremental-search-backward

#
# aliases
#
source ~/.aliases

#
# syntax highlighting
#
# source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

#
# start-up programs
#
# export PALS_DAYS=10
# pals

#
# completion
#
autoload -U compinit
compinit

#
# rbenv
#
eval "$(rbenv init -)"

# 
# deno
#
export DENO_INSTALL="/Users/oscar/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"

